### ISSUE TITLE
Где что сломано?

### ISSUE THREAD

**Issue by Rabinzon** [apsavin/bnsf-project-stub#7]
Запустил по инструкции. 
`events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/-project-name/bundles/index/freezing/_index.css'
    at Error (native)
`
дальше

`
TypeError: vow.promise is not a function

15:01:39.791 - [failed] [bundles/index/index.routes.js] routes

15:01:39.791 - [failed] [bundles/index/index.routes-private.js] routes

15:01:39.822 - [rebuild] [bundles/index/index.deps.js] deps

15:01:39.831 - [rebuild] [bundles/index/index.files] files

15:01:39.831 - [rebuild] [bundles/index/index.dirs] files

15:01:39.942 - [failed] [bundles/index/index.bemtree.js] bemtree

15:01:39.961 - [rebuild] [bundles/index/index.browser.js] js-borschik-include

15:01:39.962 - [rebuild] [bundles/index/index.noprefix.css] css-stylus`

**Comment by apsavin** [comment]
Fixed.
Please, update your project and try again.

**Comment by Rabinzon** [comment]
It's not working.
@vedro:~/Documents/folder$ gulp
[17:56:48] Using gulpfile ~/Documents/folder/gulpfile.js
[17:56:48] Starting 'build'...
[17:56:49] Starting 'watch'...
[17:56:49] Finished 'watch' after 11 ms
17:56:49.698 - build started
17:56:49.745 - [rebuild] [bundles/index/index.bemdecl.js] file-provider
17:56:49.748 - [rebuild] [bundles/index/index.routing.yml] file-provider
17:56:49.749 - [rebuild] [bundles/index/index.api.routing.yml] file-provider
17:56:49.813 - [rebuild] [bundles/index/index.levels] levels
17:56:49.824 - [failed] [bundles/index/index.pages.node.js] pages
17:56:49.824 - [failed] [bundles/index/index.controllers.node.js] controllers
17:56:49.824 - [failed] [bundles/index/index.pages.js] pages-browser
17:56:49.825 - [rebuild] [bundles/index/index.parameters.js] parameters
17:56:49.829 - [failed] [bundles/index/index.node.js] node-js-with-sources
17:56:49.829 - [failed] [bundles/index/index.pre.js] file-merge
17:56:49.831 - [failed] [bundles/index/_index.node.js] prepend-modules
17:56:49.831 - [failed] [bundles/index/index.js] prepend-modules
17:56:49.839 - [failed] [bundles/index/freezing/_index.js] borschik
17:56:49.839 - build failed
17:56:49.840 - [failed] [bundles/index/index.config.node.js] node-configs
17:56:49.840 - build failed
[TypeError: vow.promise is not a function]
[17:56:49] Finished 'build' after 1.68 s
[17:56:49] Starting 'run'...
[17:56:49] Finished 'run' after 5.22 ms
[17:56:49] Starting 'default'...
[17:56:49] Finished 'default' after 12 μs
17:56:49.849 - [failed] [bundles/index/index.routes-private.js] routes
17:56:49.849 - [failed] [bundles/index/index.routes.js] routes
17:56:49.908 - [rebuild] [bundles/index/index.deps.js] deps
17:56:49.917 - [rebuild] [bundles/index/index.files] files
17:56:49.917 - [rebuild] [bundles/index/index.dirs] files
17:56:50.124 - [failed] [bundles/index/index.bemtree.js] bemtree
17:56:50.131 - [rebuild] [bundles/index/index.noprefix.css] css-stylus
17:56:50.132 - [rebuild] [bundles/index/index.browser.js] js-borschik-include
Server started at http://0.0.0.0:8080

Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
17:56:50.216 - [rebuild] [bundles/index/index.css] css-autoprefixer
17:56:50.476 - [rebuild] [bundles/index/freezing/_index.css] borschik
17:56:50.794 - [rebuild] [bundles/index/index.bemhtml.js] bemhtml
17:57:04.957 - [rebuild] [bundles/index/index.bemdecl.js] file-provider

17:57:04.960 - [rebuild] [bundles/index/index.routing.yml] file-provider

17:57:04.960 - [rebuild] [bundles/index/index.api.routing.yml] file-provider

17:57:05.020 - [rebuild] [bundles/index/index.levels] levels

17:57:05.031 - [failed] [bundles/index/index.pages.node.js] pages

17:57:05.031 - [failed] [bundles/index/index.controllers.node.js] controllers
17:57:05.031 - [failed] [bundles/index/index.pages.js] pages-browser

17:57:05.031 - [rebuild] [bundles/index/index.parameters.js] parameters

17:57:05.033 - [failed] [bundles/index/index.node.js] node-js-with-sources
17:57:05.034 - [failed] [bundles/index/index.pre.js] file-merge

17:57:05.036 - [failed] [bundles/index/_index.node.js] prepend-modules

17:57:05.037 - [failed] [bundles/index/index.js] prepend-modules

17:57:05.043 - [failed] [bundles/index/freezing/_index.js] borschik

17:57:05.044 - [failed] [bundles/index/index.config.node.js] node-configs

TypeError: vow.promise is not a function
    at Object.Queue.enqueue (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/vow-queue/lib/queue.js:56:31)
    at Object.wrapper [as write] (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/node_modules/vow-fs/lib/fs.js:39:39)
    at _saveFunc (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/lib/build-flow.js:51:26)
    at resultTechMethods._saveBuildResult (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/lib/build-flow.js:608:33)
    at /home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/lib/build-flow.js:671:47
    at Array.<anonymous> (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Immediate.callFns [as _onImmediate] (/home/rabinzon/Documents/folder/libs/bnsf/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

17:57:05.045 - [failed] [bundles/index/index.routes.js] routes

17:57:05.045 - [failed] [bundles/index/index.routes-private.js] routes

17:57:05.082 - [rebuild] [bundles/index/index.deps.js] deps

17:57:05.092 - [rebuild] [bundles/index/index.files] files

17:57:05.093 - [rebuild] [bundles/index/index.dirs] files

17:57:05.230 - [failed] [bundles/index/index.bemtree.js] bemtree

17:57:05.242 - [rebuild] [bundles/index/index.browser.js] js-borschik-include

17:57:05.243 - [rebuild] [bundles/index/index.noprefix.css] css-stylus

Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
`
Ubuntu 14.04
node 5.8 
npm 3.7

**Comment by apsavin** [comment]
Well, can you try it with node 4.x and npm 2.x for a while? You can use [nvm](https://github.com/creationix/nvm) to install several node versions on one machine.

**Comment by apsavin** [comment]
https://github.com/apsavin/bnsf/issues/45 I need some time to adopt it for new version of npm.

**Comment by Rabinzon** [comment]
Thanks, it's work now!

**Comment by apsavin** [comment]
You're welcome! Feel free to ask any questions on https://ru.bem.info/forum/ - and I'll try to answer and help.

**Comment by apsavin** [comment]
@Rabinzon JFYI bnsf works with node v5 and npm 3 in branch node-5 https://github.com/apsavin/bnsf/tree/node-5
Will be merged soon.

**Comment by apsavin** [comment]
Merged, you can use bnsf#0.9.0

**Comment by apsavin** [comment]
@Rabinzon I've updated this repo: it works on node 5 and npm 3 as well now
